In [2]:
import pandas as pd

In [5]:
df = pd.read_csv('./dataset/full_preprocessed_data.csv')

In [6]:
df

,loan_id,date,amount,duration,payments,frequency,balance_mean,balance_max,balance_min,balance_std,...,expected_income_to_payments_ratio,actual_income_to_payments_ratio,ratio_actual_salary_to_expected,log_credit_min,log_sanctions_std,log_CAB_sum,log_CAB_mean,log_max_value_in_account_to_loan_ratio,log_criminality_growth,status
0,5314,1993-07-05,96396,12,8033,2,12250.000000,20100.0,1100.0,8330.866301,...,0.100108,0.625545,6.248705,7.003247,0.0,0.000000,0.000000,0.113178,0.034255,-1
1,5316,1993-07-11,165960,36,4610,1,52083.859459,120512.8,700.0,29122.059454,...,0.075958,0.930948,12.256075,1.131402,0.0,0.000000,0.000000,0.493154,0.034077,1
2,6863,1993-07-28,127080,60,2118,1,30060.954167,49590.4,800.0,11520.184451,...,0.017863,-0.825590,-46.218502,3.887730,0.0,11.154907,9.545526,0.263553,0.036618,1
3,5325,1993-08-03,105804,36,2939,1,41297.480000,65898.5,1000.0,14151.260443,...,0.086509,0.511625,5.914127,4.890349,0.0,11.649282,9.857566,0.427978,0.034419,1
4,7240,1993-09-06,274740,60,4579,2,57188.211111,122893.1,600.0,25256.665817,...,0.137075,0.959146,6.997234,4.347694,0.0,12.523023,10.731282,0.306472,0.034960,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
323,6818,1996-12-12,155616,48,3242,1,44197.509884,75294.1,200.0,11044.494392,...,0.164687,0.741067,4.499842,3.173878,0.0,0.000000,0.000000,0.333010,0.034117,1
324,5625,1996-12-15,222180,60,3703,1,55230.444068,130659.1,800.0,26510.559286,...,0.199005,0.869667,4.370069,4.638605,0.0,0.000000,0.000000,0.405061,0.037574,-1
325,6805,1996-12-21,45024,48,938,1,41994.907692,63659.3,800.0,13151.510254,...,0.484897,1.255062,2.588307,3.718438,0.0,0.000000,0.000000,0.843812,0.036875,1
326,7233,1996-12-25,115812,36,3217,1,56646.516129,119527.2,1100.0,21971.162852,...,0.218293,1.729203,7.921462,3.937691,0.0,0.000000,0.000000,0.664437,0.036499,1
327,7308,1996-12-27,129408,24,5392,1,30869.781308,56055.6,1000.0,11709.142375,...,0.051465,1.010295,19.630666,3.918005,0.0,0.000000,0.000000,0.296012,0.034596,1